name: makharej_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.11
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  fpdart: ^0.4.0
  equatable: ^2.0.5
  google_sign_in: ^5.0.2
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  bloc_test: ^9.1.1
  mockito: ^5.3.2
  firebase_auth_mocks: ^0.10.3
  google_sign_in_mocks: ^0.2.1
  mock_exceptions: ^0.8.2
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
