final mockCategoriesList = [
  {
    'id': '1',
    'title': 'Groceries',
    'currentTotalValue': 150.0,
    'monthlyTotalValuePrediction': 300.0,
    'color': '#3498db',
    'iconName': 'shopping_cart',
    'isIncome': false,
    'familyID': 'family1',
    'createdBy': 'user1',
  },
  {
    'id': '2',
    'title': 'Salary',
    'currentTotalValue': 3500.0,
    'monthlyTotalValuePrediction': 4000.0,
    'color': '#2ecc71',
    'iconName': 'attach_money',
    'isIncome': true,
    'familyID': 'family1',
    'createdBy': 'user1',
  },
  {
    'id': '3',
    'title': 'Utilities',
    'currentTotalValue': 80.0,
    'monthlyTotalValuePrediction': 120.0,
    'color': '#e74c3c',
    'iconName': 'settings',
    'isIncome': false,
    'familyID': 'family2',
    'createdBy': 'user2',
  },
  {
    'id': '4',
    'title': 'Freelance Work',
    'currentTotalValue': 800.0,
    'monthlyTotalValuePrediction': 1000.0,
    'color': '#f39c12',
    'iconName': 'work',
    'isIncome': true,
    'familyID': 'family2',
    'createdBy': 'user2',
  },
  {
    'id': '5',
    'title': 'Entertainment',
    'currentTotalValue': 50.0,
    'monthlyTotalValuePrediction': 80.0,
    'color': '#9b59b6',
    'iconName': 'movie',
    'isIncome': false,
    'familyID': 'family3',
    'createdBy': 'user3',
  },
  {
    'id': '6',
    'title': 'Investments',
    'currentTotalValue': 1200.0,
    'monthlyTotalValuePrediction': 1500.0,
    'color': '#27ae60',
    'iconName': 'trending_up',
    'isIncome': true,
    'familyID': 'family3',
    'createdBy': 'user3',
  },
  {
    'id': '7',
    'title': 'Dining Out',
    'currentTotalValue': 75.0,
    'monthlyTotalValuePrediction': 100.0,
    'color': '#e67e22',
    'iconName': 'restaurant',
    'isIncome': false,
    'familyID': 'family4',
    'createdBy': 'user4',
  },
];
